
[tool.flake8]
max-line-length = 140


[tool.pylint]
max-line-length = 140
disable = [
"C0116",  # Missing function or method docstring
"C0114",  # Missing module docstring
]
min-public-methods = 1
max-public-methods = 20



[tool.ruff]
line-length = 140

[tool.ruff.lint]
select = [
    "E",  # pycodestyle
    "F",  # Pyflakes
    "UP",  # pyupgrade
    "B",  # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",  # isort
    "ANN"  # flake8-annotations
]
ignore = [
"ANN101",  # Missing type annotation for self in method
"ANN102",  # Missing type annotation for cls in classmethod
"ANN204",  # __init__ return type
]

[tool.ruff.lint.flake8-annotations]
ignore-fully-untyped = false

